blank_issues_enabled: false
contact_links:
    - name: Support question â“
      url: https://github.com/Zmyslny/laravel-inline-scripts/discussions/new?category=q-a
      about: Please open a new discussion instead. Thank you.